// The trade-and-town search box. The same markup is on /kerko (rendered by the Worker) and, once the directory is
// open, on the homepage (written by scripts/build.mjs), so this module imports nothing generated by the build.

import { TOWNS, TRADES } from '../src/mjeshtri/catalog.js';

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

const options = (list, selected) => list
  .map((x) => `<option value="${esc(x.slug)}"${x.slug === selected ? ' selected' : ''}>${esc(x.label)}</option>`).join('');

/** @param {{ trade?: string, town?: string, id?: string }} o  id keeps the labels unique when a page has two boxes. */
export function searchForm({ trade = '', town = '', id = 'kerko' } = {}) {
  return `<form class="find" action="/kerko" method="get" role="search" aria-label="Kërko mjeshtër" data-find>
  <div class="find-field">
    <label class="find-label" for="${id}-zanati">Çka të duhet?</label>
    <select class="find-select" id="${id}-zanati" name="zanati"><option value="">Të gjitha zanatet</option>${options(TRADES, trade)}</select>
  </div>
  <div class="find-field">
    <label class="find-label" for="${id}-komuna">Ku?</label>
    <select class="find-select" id="${id}-komuna" name="komuna"><option value="">Gjithë Kosova</option>${options(TOWNS, town)}</select>
  </div>
  <button class="btn btn-primary find-go" type="submit">Kërko</button>
</form>`;
}
